// <auto-generated />
using System;
using CleanFoodVietAPI.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleanFoodVietAPI.Data.Migrations
{
    [DbContext(typeof(CleanFoodVietDbContext))]
    [Migration("20250605015228_UpdateServiceFeatureStatusAsString")]
    partial class UpdateServiceFeatureStatusAsString
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Account", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("AccountId")
                        .HasName("PK_Account");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Account_Email");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Account_PhoneNumber");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_Account_RoleId");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Address", b =>
                {
                    b.Property<string>("AddressId")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("AddessLine1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AddessLine2")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("AddressId")
                        .HasName("PK_Address");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("IX_Address_UserId");

                    b.ToTable("Address", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Appointment", b =>
                {
                    b.Property<string>("AppointmentId")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime");

                    b.Property<string>("AppointmentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CancelledBy")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("GardenerId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RetailerId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("AppointmentId")
                        .HasName("PK_Appointment");

                    b.HasIndex("GardenerId")
                        .HasDatabaseName("IX_Appointment_GardenerId");

                    b.HasIndex("RetailerId")
                        .HasDatabaseName("IX_Appointment_RetailerId");

                    b.ToTable("Appointment", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Cart", b =>
                {
                    b.Property<string>("CartId")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("GardenerId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("RetailerId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("CartId")
                        .HasName("PK_Cart");

                    b.HasIndex("GardenerId")
                        .HasDatabaseName("IX_Cart_GardenerId");

                    b.HasIndex("RetailerId")
                        .HasDatabaseName("IX_Cart_RetailerId");

                    b.ToTable("Cart", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.CartItem", b =>
                {
                    b.Property<string>("CartItemId")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("CartId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(14,2)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("ProductUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("CartItemId")
                        .HasName("PK_CartItem");

                    b.HasIndex("CartId")
                        .HasDatabaseName("IX_CartItem_CartId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_CartItem_PostId");

                    b.ToTable("CartItem", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Certificate", b =>
                {
                    b.Property<string>("CertificateId")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime");

                    b.Property<string>("GardenerId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime");

                    b.Property<string>("IssuingAuthority")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("CertificateId")
                        .HasName("PK_Certificate");

                    b.HasIndex("GardenerId")
                        .HasDatabaseName("IX_Certificate_GardenerId");

                    b.ToTable("Certificate", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.ChatMessage", b =>
                {
                    b.Property<string>("ChatMessageId")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("MessageStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MessageText")
                        .HasColumnType("text");

                    b.Property<string>("ReceiverId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime");

                    b.HasKey("ChatMessageId")
                        .HasName("PK_ChatMessage");

                    b.HasIndex("ReceiverId")
                        .HasDatabaseName("IX_ChatMessage_ReceiverId");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("IX_ChatMessage_SenderId");

                    b.ToTable("ChatMessage", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Favorite", b =>
                {
                    b.Property<string>("FavoriteId")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("RetailerId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.HasKey("FavoriteId")
                        .HasName("PK_Favorite");

                    b.HasIndex("PostId")
                        .HasDatabaseName("IX_Favorite_PostId");

                    b.HasIndex("RetailerId")
                        .HasDatabaseName("IX_Favorite_RetailerId");

                    b.ToTable("Favorite", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.GardenerIncome", b =>
                {
                    b.Property<string>("GardenerIncomeId")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("GardenerId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(14,2)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime");

                    b.HasKey("GardenerIncomeId")
                        .HasName("PK_GardenerIncome");

                    b.HasIndex("GardenerId")
                        .HasDatabaseName("IX_GardenerIncome_GardenerId");

                    b.ToTable("GardenerIncome", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Notification", b =>
                {
                    b.Property<string>("NotificationId")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Link")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("NotificationId")
                        .HasName("PK_Notification");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("IX_Notification_AccountId");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Order", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("GardenerId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("RetailerId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(14,2)");

                    b.HasKey("OrderId")
                        .HasName("PK_Order");

                    b.HasIndex("GardenerId")
                        .HasDatabaseName("IX_Order_GardenerId");

                    b.HasIndex("RetailerId")
                        .HasDatabaseName("IX_Order_RetailerId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.OrderItem", b =>
                {
                    b.Property<string>("OrderItemId")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(14,2)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("ProductUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("ShippingStatus")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.HasKey("OrderItemId")
                        .HasName("PK_OrderItem");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_OrderItem_OrderId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_OrderItem_ProductId");

                    b.ToTable("OrderItem", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.PackageServiceFeature", b =>
                {
                    b.Property<string>("PackageServiceFeatureId")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("FeatureValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ServiceFeatureId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("ServicePackageId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.HasKey("PackageServiceFeatureId")
                        .HasName("PK_PackageServiceFeature");

                    b.HasIndex("ServiceFeatureId")
                        .HasDatabaseName("IX_PackageServiceFeature_ServiceFeatureId");

                    b.HasIndex("ServicePackageId")
                        .HasDatabaseName("IX_PackageServiceFeature_ServicePackageId");

                    b.ToTable("PackageServiceFeature", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Post", b =>
                {
                    b.Property<string>("PostId")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("GardenerId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<DateTime>("HarvestDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("PostEndDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("PostId")
                        .HasName("PK_Post");

                    b.HasIndex("GardenerId")
                        .HasDatabaseName("IX_Post_GardenerId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_Post_CategoryId");

                    b.ToTable("Post", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.PostMedia", b =>
                {
                    b.Property<string>("PostMediaId")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("MediumType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MediumUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("char(26)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime");

                    b.HasKey("PostMediaId")
                        .HasName("PK_PostMedia");

                    b.HasIndex("PostId");

                    b.ToTable("PostMedia", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Product", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("GardenerId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("ProductCategoryId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("ProductId")
                        .HasName("PK_Product");

                    b.HasIndex("GardenerId");

                    b.HasIndex("ProductCategoryId");

                    b.HasIndex("ProductName")
                        .HasDatabaseName("IX_Product_ProductName");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.ProductCategory", b =>
                {
                    b.Property<string>("ProductCategoryId")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ProductCategoryId")
                        .HasName("PK_ProductCategory");

                    b.ToTable("ProductCategory", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.ProductPrice", b =>
                {
                    b.Property<string>("ProductPriceId")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<DateTime>("AvailabledDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Productd")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("ProductPriceId")
                        .HasName("PK_ProductPrice");

                    b.HasIndex("Productd")
                        .HasDatabaseName("IX_ProductPrice_ProductId");

                    b.ToTable("ProductPrice", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Report", b =>
                {
                    b.Property<string>("ReportId")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("ReportId")
                        .HasName("PK_Report");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("IX_Report_AccountId");

                    b.ToTable("Report", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Review", b =>
                {
                    b.Property<string>("ReviewId")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("OrderItemId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("RetailerId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.HasKey("ReviewId")
                        .HasName("PK_Review");

                    b.HasIndex("OrderItemId")
                        .HasDatabaseName("IX_Review_OrderItemId");

                    b.HasIndex("RetailerId")
                        .HasDatabaseName("IX_Review_RetailerId");

                    b.ToTable("Review", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Role", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK_Role");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.ServiceFeature", b =>
                {
                    b.Property<string>("ServiceFeatureId")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("DefaultValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ServiceFeatureName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ServiceFeatureId")
                        .HasName("PK_ServiceFeature");

                    b.ToTable("ServiceFeature", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.ServicePackage", b =>
                {
                    b.Property<string>("ServicePackageId")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("ServicePackageId")
                        .HasName("PK_ServicePackage");

                    b.ToTable("ServicePackage", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.ServicePackageOrder", b =>
                {
                    b.Property<string>("ServicePackageOrderId")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("GardenerId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("ServicePackageId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ServicePackageOrderId")
                        .HasName("PK_ServicePackageOrder");

                    b.HasIndex("GardenerId")
                        .HasDatabaseName("IX_ServicePackageOrder_GardenerId");

                    b.HasIndex("ServicePackageId")
                        .HasDatabaseName("IX_ServicePackageOrder_ServicePackageId");

                    b.ToTable("ServicePackageOrder", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.ServicePackageOrderPayment", b =>
                {
                    b.Property<string>("ServicePackageOrderPaymentId")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ServicePackageOrderId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ServicePackageOrderPaymentId")
                        .HasName("PK_ServicePackageOrderPayment");

                    b.HasIndex("ServicePackageOrderId")
                        .HasDatabaseName("IX_ServicePackageOrderPayment_ServicePackageOrderId");

                    b.ToTable("ServicePackageOrderPayment", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.SubscriptionContract", b =>
                {
                    b.Property<string>("SubscriptionId")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("GardenerId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("ServicePackageId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SubscriptionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("SubscriptionId")
                        .HasName("PK_SubscriptionContract");

                    b.HasIndex("GardenerId")
                        .HasDatabaseName("IX_SubscriptionContract_GardenerId");

                    b.HasIndex("ServicePackageId")
                        .HasDatabaseName("IX_SubscriptionContract_ServicePackageId");

                    b.ToTable("SubscriptionContract", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.SystemLog", b =>
                {
                    b.Property<string>("LogId")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AdminId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Desctiption")
                        .HasColumnType("text");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("LogId")
                        .HasName("PK_SystemLog");

                    b.HasIndex("AdminId")
                        .HasDatabaseName("IX_SystemLog_AdminId");

                    b.ToTable("SystemLog", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Account", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Account_Role");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Address", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.Account", "Account")
                        .WithMany("Addresses")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Address_Account");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Appointment", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.Account", "Gardener")
                        .WithMany("GardenerAppointments")
                        .HasForeignKey("GardenerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Appointment_Gardeners");

                    b.HasOne("CleanFoodVietAPI.Data.Entities.Account", "Retailer")
                        .WithMany("RetailerAppointments")
                        .HasForeignKey("RetailerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Appointment_Retailers");

                    b.Navigation("Gardener");

                    b.Navigation("Retailer");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Cart", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.Account", "Gardener")
                        .WithMany("GardenerCarts")
                        .HasForeignKey("GardenerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Cart_Gardeners");

                    b.HasOne("CleanFoodVietAPI.Data.Entities.Account", "Retailer")
                        .WithMany("RetailerCarts")
                        .HasForeignKey("RetailerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Cart_Retailers");

                    b.Navigation("Gardener");

                    b.Navigation("Retailer");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.CartItem", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CartItem_Cart");

                    b.HasOne("CleanFoodVietAPI.Data.Entities.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CartItem_Product");

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Certificate", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.Account", "Account")
                        .WithMany("Certificates")
                        .HasForeignKey("GardenerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Certificate_Account");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.ChatMessage", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.Account", "Receiver")
                        .WithMany("ReceiverMessages")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ChatMessage_Receiver");

                    b.HasOne("CleanFoodVietAPI.Data.Entities.Account", "Sender")
                        .WithMany("SenderMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ChatMessage_Sender");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Favorite", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.Post", "Post")
                        .WithMany("Favorites")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Favorite_Post");

                    b.HasOne("CleanFoodVietAPI.Data.Entities.Account", "Account")
                        .WithMany("Favorites")
                        .HasForeignKey("RetailerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Favorite_Account");

                    b.Navigation("Account");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.GardenerIncome", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.Account", "Account")
                        .WithMany("GardenerIncomes")
                        .HasForeignKey("GardenerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_GardenerIncome_Account");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Notification", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.Account", "Account")
                        .WithMany("Notifications")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Notification_Account");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Order", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.Account", "Gardener")
                        .WithMany("GardenerOrders")
                        .HasForeignKey("GardenerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Order_Gardeners");

                    b.HasOne("CleanFoodVietAPI.Data.Entities.Account", "Retailer")
                        .WithMany("RetailerOrders")
                        .HasForeignKey("RetailerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Order_Retailers");

                    b.Navigation("Gardener");

                    b.Navigation("Retailer");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.OrderItem", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OrderItem_Order");

                    b.HasOne("CleanFoodVietAPI.Data.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_OrderItem_Product");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.PackageServiceFeature", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.ServiceFeature", "ServiceFeature")
                        .WithMany("ServicePackageFeatures")
                        .HasForeignKey("ServiceFeatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PackageServiceFeature_ServiceFeature");

                    b.HasOne("CleanFoodVietAPI.Data.Entities.ServicePackage", "ServicePackage")
                        .WithMany("ServicePackageFeatures")
                        .HasForeignKey("ServicePackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PackageServiceFeature_ServicePackage");

                    b.Navigation("ServiceFeature");

                    b.Navigation("ServicePackage");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Post", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.Account", "Account")
                        .WithMany("Posts")
                        .HasForeignKey("GardenerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Post_Account");

                    b.HasOne("CleanFoodVietAPI.Data.Entities.Product", "Product")
                        .WithMany("Posts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Post_Product");

                    b.Navigation("Account");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.PostMedia", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.Post", "Post")
                        .WithMany("PostMedias")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PostMedia_Post");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Product", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.Account", "Gardener")
                        .WithMany("Products")
                        .HasForeignKey("GardenerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Product_GardenerAccount");

                    b.HasOne("CleanFoodVietAPI.Data.Entities.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Product_ProductCategory");

                    b.Navigation("Gardener");

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.ProductPrice", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.Product", "Product")
                        .WithMany("ProductPrices")
                        .HasForeignKey("Productd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProductPrice_Product");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Report", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.Account", "Account")
                        .WithMany("Reports")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Report_Account");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Review", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.OrderItem", "OrderItem")
                        .WithMany("Reviews")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Review_OrderItem");

                    b.HasOne("CleanFoodVietAPI.Data.Entities.Account", "Account")
                        .WithMany("Reviews")
                        .HasForeignKey("RetailerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Review_Account");

                    b.Navigation("Account");

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.ServicePackageOrder", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.Account", "Gardener")
                        .WithMany("ServicePackageOrders")
                        .HasForeignKey("GardenerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ServicePackageOrder_Account");

                    b.HasOne("CleanFoodVietAPI.Data.Entities.ServicePackage", "ServicePackage")
                        .WithMany("ServicePackageOrders")
                        .HasForeignKey("ServicePackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ServicePackageOrder_ServicePackage");

                    b.Navigation("Gardener");

                    b.Navigation("ServicePackage");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.ServicePackageOrderPayment", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.ServicePackageOrder", "ServicePackageOrder")
                        .WithMany("ServicePackageOrderPayments")
                        .HasForeignKey("ServicePackageOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ServicePackageOrderPayment_ServicePackageOrder");

                    b.Navigation("ServicePackageOrder");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.SubscriptionContract", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.Account", "Account")
                        .WithMany("ServicePackageContracts")
                        .HasForeignKey("GardenerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SubscriptionContract_Account");

                    b.HasOne("CleanFoodVietAPI.Data.Entities.ServicePackage", "ServicePackage")
                        .WithMany("SubscriptionContracts")
                        .HasForeignKey("ServicePackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SubscriptionContract_ServicePackage");

                    b.Navigation("Account");

                    b.Navigation("ServicePackage");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.SystemLog", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.Account", "Admin")
                        .WithMany("SystemLogs")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SystemLog_Account");

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Account", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Certificates");

                    b.Navigation("Favorites");

                    b.Navigation("GardenerAppointments");

                    b.Navigation("GardenerCarts");

                    b.Navigation("GardenerIncomes");

                    b.Navigation("GardenerOrders");

                    b.Navigation("Notifications");

                    b.Navigation("Posts");

                    b.Navigation("Products");

                    b.Navigation("ReceiverMessages");

                    b.Navigation("Reports");

                    b.Navigation("RetailerAppointments");

                    b.Navigation("RetailerCarts");

                    b.Navigation("RetailerOrders");

                    b.Navigation("Reviews");

                    b.Navigation("SenderMessages");

                    b.Navigation("ServicePackageContracts");

                    b.Navigation("ServicePackageOrders");

                    b.Navigation("SystemLogs");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.OrderItem", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Post", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("PostMedias");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");

                    b.Navigation("Posts");

                    b.Navigation("ProductPrices");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Role", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.ServiceFeature", b =>
                {
                    b.Navigation("ServicePackageFeatures");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.ServicePackage", b =>
                {
                    b.Navigation("ServicePackageFeatures");

                    b.Navigation("ServicePackageOrders");

                    b.Navigation("SubscriptionContracts");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.ServicePackageOrder", b =>
                {
                    b.Navigation("ServicePackageOrderPayments");
                });
#pragma warning restore 612, 618
        }
    }
}
