// <auto-generated />
using System;
using CleanFoodVietAPI.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleanFoodVietAPI.Data.Migrations
{
    [DbContext(typeof(CleanFoodVietDbContext))]
    [Migration("20250522083157_DBPreSetupV1")]
    partial class DBPreSetupV1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK_Account");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Account_Email");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Account_PhoneNumber");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_Account_RoleId");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Address", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("AddessLine1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AddessLine2")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("PK_Address");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Address_UserId");

                    b.ToTable("Address", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Appointment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime");

                    b.Property<string>("AppointmentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("GardenerId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RetailerId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK_Appointment");

                    b.HasIndex("GardenerId")
                        .HasDatabaseName("IX_Appointment_GardenerId");

                    b.HasIndex("RetailerId")
                        .HasDatabaseName("IX_Appointment_RetailerId");

                    b.ToTable("Appointment", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Cart", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("GardenerId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("RetailerId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK_Cart");

                    b.HasIndex("GardenerId")
                        .HasDatabaseName("IX_Cart_GardenerId");

                    b.HasIndex("RetailerId")
                        .HasDatabaseName("IX_Cart_RetailerId");

                    b.ToTable("Cart", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.CartItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("CartId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK_CartItem");

                    b.HasIndex("CartId")
                        .HasDatabaseName("IX_CartItem_CartId");

                    b.HasIndex("PostId")
                        .HasDatabaseName("IX_CartItem_PostId");

                    b.ToTable("CartItem", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Certificate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime");

                    b.Property<string>("GardenerId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime");

                    b.Property<string>("IssuingAuthority")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK_Certificate");

                    b.HasIndex("GardenerId")
                        .HasDatabaseName("IX_Certificate_GardenerId");

                    b.ToTable("Certificate", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.ChatMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("ChatRoomId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("MessageStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MessageText")
                        .HasColumnType("text");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK_ChatMessage");

                    b.HasIndex("ChatRoomId")
                        .HasDatabaseName("IX_ChatMessage_ChatRoomId");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("IX_ChatMessage_SenderId");

                    b.ToTable("ChatMessage", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.ChatRoom", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("GardenerId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime");

                    b.Property<string>("RetailerId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("PK_ChatRoom");

                    b.HasIndex("GardenerId")
                        .HasDatabaseName("IX_ChatRoom_GardenerId");

                    b.HasIndex("RetailerId")
                        .HasDatabaseName("IX_ChatRoom_RetailerId");

                    b.ToTable("ChatRoom", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.CleanFoodCategory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PK_CleanFoodCategory");

                    b.ToTable("CleanFoodCategory", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Favorite", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("RetailerId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("PK_Favorite");

                    b.HasIndex("PostId")
                        .HasDatabaseName("IX_Favorite_PostId");

                    b.HasIndex("RetailerId")
                        .HasDatabaseName("IX_Favorite_RetailerId");

                    b.ToTable("Favorite", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Link")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id")
                        .HasName("PK_Notification");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("IX_Notification_AccountId");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("GardenerId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("RetailerId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK_Order");

                    b.HasIndex("GardenerId")
                        .HasDatabaseName("IX_Order_GardenerId");

                    b.HasIndex("RetailerId")
                        .HasDatabaseName("IX_Order_RetailerId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.OrderItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PK_OrderItem");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_OrderItem_OrderId");

                    b.HasIndex("PostId")
                        .HasDatabaseName("IX_OrderItem_PostId");

                    b.ToTable("OrderItem", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Post", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<decimal>("AvgRating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("GardenerId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<DateTime>("HarvestDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProductPrice")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ShippingCost")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PK_Post");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_Post_CategoryId");

                    b.HasIndex("GardenerId")
                        .HasDatabaseName("IX_Post_GardenerId");

                    b.ToTable("Post", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.PostMedium", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("MediumType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MediumUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("char(26)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK_PostMedium");

                    b.HasIndex("PostId");

                    b.ToTable("PostMedium", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.RefreshToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id")
                        .HasName("PK_RefreshToken");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("IX_RefreshToken_AccountId");

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Report", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PK_Report");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("IX_Report_AccountId");

                    b.ToTable("Report", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Review", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("OrderItemId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("RetailerId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("PK_Review");

                    b.HasIndex("OrderItemId")
                        .HasDatabaseName("IX_Review_OrderItemId");

                    b.HasIndex("RetailerId")
                        .HasDatabaseName("IX_Review_RetailerId");

                    b.ToTable("Review", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_Role");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.ServiceFeature", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("DefaultValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ServiceFeatureName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PK_ServiceFeature");

                    b.ToTable("ServiceFeature", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.ServicePackage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK_ServicePackage");

                    b.ToTable("ServicePackage", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.ServicePackageContract", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("GardenerId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("ServicePackageId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK_ServicePackageContract");

                    b.HasIndex("GardenerId")
                        .HasDatabaseName("IX_ServicePackageContract_GardenerId");

                    b.HasIndex("ServicePackageId")
                        .HasDatabaseName("IX_ServicePackageContract_ServicePackageId");

                    b.ToTable("ServicePackageContract", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.ServicePackageFeature", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("FeatureValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ServiceFeatureId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("ServicePackageId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("PK_ServicePackageFeature");

                    b.HasIndex("ServiceFeatureId")
                        .HasDatabaseName("IX_ServicePackageFeature_ServiceFeatureId");

                    b.HasIndex("ServicePackageId")
                        .HasDatabaseName("IX_ServicePackageFeature_ServicePackageId");

                    b.ToTable("ServicePackageFeature", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.ServicePackageOrder", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("GardenerId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("ServicePackageId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id")
                        .HasName("PK_ServicePackageOrder");

                    b.HasIndex("GardenerId")
                        .HasDatabaseName("IX_ServicePackageOrder_GardenerId");

                    b.HasIndex("ServicePackageId")
                        .HasDatabaseName("IX_ServicePackageOrder_ServicePackageId");

                    b.ToTable("ServicePackageOrder", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.ServicePackageOrderPayment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ServicePackageOrderId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK_ServicePackageOrderPayment");

                    b.HasIndex("ServicePackageOrderId")
                        .HasDatabaseName("IX_ServicePackageOrderPayment_ServicePackageOrderId");

                    b.ToTable("ServicePackageOrderPayment", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.SystemLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AdminId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Desctiption")
                        .HasColumnType("text");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .IsFixedLength();

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_SystemLog");

                    b.HasIndex("AdminId")
                        .HasDatabaseName("IX_SystemLog_AdminId");

                    b.ToTable("SystemLog", (string)null);
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Account", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Account_Role");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Address", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.Account", "Account")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Address_Account");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Appointment", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.Account", "Gardener")
                        .WithMany("GardenerAppointments")
                        .HasForeignKey("GardenerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Appointment_Gardeners");

                    b.HasOne("CleanFoodVietAPI.Data.Entities.Account", "Retailer")
                        .WithMany("RetailerAppointments")
                        .HasForeignKey("RetailerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Appointment_Retailers");

                    b.Navigation("Gardener");

                    b.Navigation("Retailer");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Cart", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.Account", "Gardener")
                        .WithMany("GardenerCarts")
                        .HasForeignKey("GardenerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Cart_Gardeners");

                    b.HasOne("CleanFoodVietAPI.Data.Entities.Account", "Retailer")
                        .WithMany("RetailerCarts")
                        .HasForeignKey("RetailerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Cart_Retailers");

                    b.Navigation("Gardener");

                    b.Navigation("Retailer");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.CartItem", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CartItem_Cart");

                    b.HasOne("CleanFoodVietAPI.Data.Entities.Post", "Post")
                        .WithMany("CartItems")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CartItem_Post");

                    b.Navigation("Cart");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Certificate", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.Account", "Account")
                        .WithMany("Certificates")
                        .HasForeignKey("GardenerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Certificate_Account");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.ChatMessage", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.ChatRoom", "ChatRoom")
                        .WithMany("ChatMessages")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ChatMessage_ChatRoom");

                    b.HasOne("CleanFoodVietAPI.Data.Entities.Account", "Account")
                        .WithMany("ChatMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ChatMessage_Account");

                    b.Navigation("Account");

                    b.Navigation("ChatRoom");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.ChatRoom", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.Account", "Gardener")
                        .WithMany("GardenerChatRooms")
                        .HasForeignKey("GardenerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ChatRoom_Gardeners");

                    b.HasOne("CleanFoodVietAPI.Data.Entities.Account", "Retailer")
                        .WithMany("RetailerChatRooms")
                        .HasForeignKey("RetailerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ChatRoom_Retailers");

                    b.Navigation("Gardener");

                    b.Navigation("Retailer");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Favorite", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.Post", "Post")
                        .WithMany("Favorites")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Favorite_Post");

                    b.HasOne("CleanFoodVietAPI.Data.Entities.Account", "Account")
                        .WithMany("Favorites")
                        .HasForeignKey("RetailerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Favorite_Account");

                    b.Navigation("Account");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Notification", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.Account", "Account")
                        .WithMany("Notifications")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Notification_Account");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Order", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.Account", "Gardener")
                        .WithMany("GardenerOrders")
                        .HasForeignKey("GardenerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Order_Gardeners");

                    b.HasOne("CleanFoodVietAPI.Data.Entities.Account", "Retailer")
                        .WithMany("RetailerOrders")
                        .HasForeignKey("RetailerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Order_Retailers");

                    b.Navigation("Gardener");

                    b.Navigation("Retailer");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.OrderItem", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OrderItem_Order");

                    b.HasOne("CleanFoodVietAPI.Data.Entities.Post", "Post")
                        .WithMany("OrderItems")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_OrderItem_Post");

                    b.Navigation("Order");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Post", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.CleanFoodCategory", "CleanFoodCategory")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Post_CleanFoodCategory");

                    b.HasOne("CleanFoodVietAPI.Data.Entities.Account", "Account")
                        .WithMany("Posts")
                        .HasForeignKey("GardenerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Post_Account");

                    b.Navigation("Account");

                    b.Navigation("CleanFoodCategory");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.PostMedium", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.Post", "Post")
                        .WithMany("PostMedia")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PostMedium_Post");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.Account", "Account")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RefreshToken_Account");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Report", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.Account", "Account")
                        .WithMany("Reports")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Report_Account");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Review", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.OrderItem", "OrderItem")
                        .WithMany("Reviews")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Review_OrderItem");

                    b.HasOne("CleanFoodVietAPI.Data.Entities.Account", "Account")
                        .WithMany("Reviews")
                        .HasForeignKey("RetailerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Review_Account");

                    b.Navigation("Account");

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.ServicePackageContract", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.Account", "Account")
                        .WithMany("ServicePackageContracts")
                        .HasForeignKey("GardenerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ServicePackageContract_Account");

                    b.HasOne("CleanFoodVietAPI.Data.Entities.ServicePackage", "ServicePackage")
                        .WithMany("ServicePackageContracts")
                        .HasForeignKey("ServicePackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ServicePackageContract_ServicePackage");

                    b.Navigation("Account");

                    b.Navigation("ServicePackage");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.ServicePackageFeature", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.ServiceFeature", "ServiceFeature")
                        .WithMany("ServicePackageFeatures")
                        .HasForeignKey("ServiceFeatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ServicePackageFeature_ServiceFeature");

                    b.HasOne("CleanFoodVietAPI.Data.Entities.ServicePackage", "ServicePackage")
                        .WithMany("ServicePackageFeatures")
                        .HasForeignKey("ServicePackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ServicePackageFeature_ServicePackage");

                    b.Navigation("ServiceFeature");

                    b.Navigation("ServicePackage");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.ServicePackageOrder", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.Account", "Account")
                        .WithMany("ServicePackageOrders")
                        .HasForeignKey("GardenerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ServicePackageOrder_Account");

                    b.HasOne("CleanFoodVietAPI.Data.Entities.ServicePackage", "ServicePackage")
                        .WithMany("ServicePackageOrders")
                        .HasForeignKey("ServicePackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ServicePackageOrder_ServicePackage");

                    b.Navigation("Account");

                    b.Navigation("ServicePackage");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.ServicePackageOrderPayment", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.ServicePackageOrder", "ServicePackageOrder")
                        .WithMany("ServicePackageOrderPayments")
                        .HasForeignKey("ServicePackageOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ServicePackageOrderPayment_ServicePackageOrder");

                    b.Navigation("ServicePackageOrder");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.SystemLog", b =>
                {
                    b.HasOne("CleanFoodVietAPI.Data.Entities.Account", "Account")
                        .WithMany("SystemLogs")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SystemLog_Account");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Account", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Certificates");

                    b.Navigation("ChatMessages");

                    b.Navigation("Favorites");

                    b.Navigation("GardenerAppointments");

                    b.Navigation("GardenerCarts");

                    b.Navigation("GardenerChatRooms");

                    b.Navigation("GardenerOrders");

                    b.Navigation("Notifications");

                    b.Navigation("Posts");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Reports");

                    b.Navigation("RetailerAppointments");

                    b.Navigation("RetailerCarts");

                    b.Navigation("RetailerChatRooms");

                    b.Navigation("RetailerOrders");

                    b.Navigation("Reviews");

                    b.Navigation("ServicePackageContracts");

                    b.Navigation("ServicePackageOrders");

                    b.Navigation("SystemLogs");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.ChatRoom", b =>
                {
                    b.Navigation("ChatMessages");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.CleanFoodCategory", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.OrderItem", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Post", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Favorites");

                    b.Navigation("OrderItems");

                    b.Navigation("PostMedia");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.Role", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.ServiceFeature", b =>
                {
                    b.Navigation("ServicePackageFeatures");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.ServicePackage", b =>
                {
                    b.Navigation("ServicePackageContracts");

                    b.Navigation("ServicePackageFeatures");

                    b.Navigation("ServicePackageOrders");
                });

            modelBuilder.Entity("CleanFoodVietAPI.Data.Entities.ServicePackageOrder", b =>
                {
                    b.Navigation("ServicePackageOrderPayments");
                });
#pragma warning restore 612, 618
        }
    }
}
