# github action to deploy clean-food api to azure

name: Deploy Test API

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: "CleanFoodAPI"

# define jobs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Install dependencies
        run: dotnet restore ./CleanFoodVietAPI.Presentation/CleanFoodVietAPI.Presentation.csproj

      - name: Build
        run: dotnet build ./CleanFoodVietAPI.Presentation/CleanFoodVietAPI.Presentation.csproj --configuration Release --no-restore

      # publish code
      - name: Publish
        run: dotnet publish ./CleanFoodVietAPI.Presentation/CleanFoodVietAPI.Presentation.csproj --configuration Release --output ./publish

      # deploy to Azure
      - name: Deploy API to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{secrets.CLEANFOOD_API_SECRET}}
          package: ./publish
